"""
DevFinalizer — dev pipeline step 5.
Assembles final artifact, writes to divisions/dev/hot/, returns artifact ref.
Provider chain: ollama:coder-7b → claude (Claude only if escalation approved).
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from runtime.config import DIVISIONS_DIR

log = logging.getLogger(__name__)


class DevFinalizer:

    def run(
        self,
        spec: str,
        generator_result: dict,
        reviewer_result: dict,
        tester_result: dict,
        summarizer_result: dict,
        task_id: str = "",
        target_file: str = "",
    ) -> dict[str, Any]:
        """
        Assemble and persist the final artifact.

        Returns:
        {
            "artifact_ref": str,          # path to written file
            "confidence": float,
            "recommendation": str,        # "approve" | "needs_revision" | "escalate"
            "approval_required": bool,
            "status": "success" | "failed",
            "provider_used": "deterministic",
            "target_file": str,           # where to apply if auto-approved
        }
        """
        code = generator_result.get("code", "")
        language = generator_result.get("language", "python")
        confidence = summarizer_result.get("overall_confidence", 0.0)
        verdict = reviewer_result.get("verdict", "fail")
        syntax_ok = tester_result.get("syntax_ok", False)

        # Determine recommendation
        if verdict == "pass" and syntax_ok and confidence >= 0.7:
            recommendation = "approve"
            approval_required = True   # Always gate on human approval
        elif verdict == "fail" or not syntax_ok:
            recommendation = "needs_revision"
            approval_required = True
        elif confidence < 0.5:
            recommendation = "escalate"
            approval_required = True
        else:
            recommendation = "approve"
            approval_required = True

        # Write artifact
        artifact_ref = ""
        try:
            hot_dir = DIVISIONS_DIR / "dev" / "hot"
            hot_dir.mkdir(parents=True, exist_ok=True)

            ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S")
            ext = _ext_for_language(language)
            artifact_name = f"dev-pipeline-{ts}{ext}"
            artifact_path = hot_dir / artifact_name

            artifact_data = {
                "task_id": task_id,
                "spec": spec,
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "language": language,
                "code": code,
                "review": reviewer_result,
                "test": tester_result,
                "summary": summarizer_result.get("summary", ""),
                "confidence": confidence,
                "recommendation": recommendation,
            }

            with open(artifact_path, "w", encoding="utf-8") as f:
                if ext == ".py" or ext == ".js":
                    f.write(f"# Generated by OpenClaw dev pipeline\n# Task: {task_id}\n# Spec: {spec}\n\n")
                    f.write(code)
                else:
                    json.dump(artifact_data, f, indent=2, ensure_ascii=False)

            artifact_ref = str(artifact_path)
            log.info("DevFinalizer: artifact written to %s", artifact_path)

        except Exception as e:
            log.error("DevFinalizer artifact write failed: %s", e)
            return {
                "artifact_ref": "",
                "confidence": confidence,
                "recommendation": recommendation,
                "approval_required": True,
                "status": "failed",
                "provider_used": "deterministic",
                "target_file": target_file,
                "error": str(e),
            }

        return {
            "artifact_ref": artifact_ref,
            "confidence": confidence,
            "recommendation": recommendation,
            "approval_required": approval_required,
            "status": "success",
            "provider_used": "deterministic",
            "target_file": target_file,
        }


def _ext_for_language(lang: str) -> str:
    return {
        "python": ".py",
        "javascript": ".js",
        "typescript": ".ts",
        "solidity": ".sol",
        "rust": ".rs",
        "go": ".go",
        "bash": ".sh",
    }.get(lang.lower(), ".txt")
